CREATE TABLE  `connections` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`name` VARCHAR( 100 ) NOT NULL ,
`host` VARCHAR( 250 ) NOT NULL ,
`user` VARCHAR( 100 ) NOT NULL ,
`pass` VARCHAR( 100 ) NOT NULL ,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`created_by` INT NULL DEFAULT NULL ,
`updated_by` INT NULL DEFAULT NULL
) ENGINE = INNODB;

CREATE TABLE  `folders` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`connection_id` INT NOT NULL ,
`path` VARCHAR( 500 ) NOT NULL ,
`name` VARCHAR( 100 ) NOT NULL ,
`description` TEXT ,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`created_by` INT NULL DEFAULT NULL ,
`updated_by` INT NULL DEFAULT NULL
) ENGINE = INNODB;

CREATE TABLE  `projects` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`name` VARCHAR( 100 ) NOT NULL ,
`url` VARCHAR( 250 ),
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`created_by` INT NULL DEFAULT NULL ,
`updated_by` INT NULL DEFAULT NULL
) ENGINE = INNODB;

CREATE TABLE  `syncs` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`project_id` INT NOT NULL ,
`primary_id` INT NOT NULL ,
`replica_id` INT NOT NULL ,
`name` VARCHAR( 100 ) NOT NULL ,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`created_by` INT NULL DEFAULT NULL ,
`updated_by` INT NULL DEFAULT NULL
) ENGINE = INNODB;
